# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: JAB Custom Github Action
        # You may pin to the exact commit or the version.
        # uses: jasonbent365/jab-github-create-custom-action@e8ad2e46adfdad20fa255ed25c528bb80228d05b
        id: pokemon
        uses: jasonbent365/jab-github-create-custom-action@v1.2
        with:
          # number of the pokemon in the pokedex
          pokemon_id: 150 # default is 1

      - name: Get the pokemon
        run: echo "${{ steps.pokemon.outputs.pokemon_name }} attack"

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Get Date YYYYMMDD
        id: date
        run: |
          echo "MY_DATE_TAG=$(date +'%Y%m%d')" >> $GITHUB_ENV
      
      - name: MY DATE TAG
        run: |
        echo "MY_DATE_TAG = " ${{ env.MY_DATE_TAG }}